#!/bin/sh
files=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(cpp|h|hpp|c)$')
if [ -z "$files" ]; then
    exit 0
fi

echo "$files" | xargs clang-format -i -style=file
echo "$files" | xargs git add
